Fix error deleting json files

diff --git a/termux-url-opener b/termux-url-opener
--- a/termux-url-opener
+++ b/termux-url-opener
@@ -85,6 +85,9 @@ while true; do
 
     # download video information, then scrape the proper information for the title or playlist name
     echo "Downloading link metadata..."
+    # cleanup json files if we get interuppted
+    trap 'rm $randid-*.info.json; trap - INT TERM; kill -s INT "$$"' INT
+    trap 'rm $randid-*.info.json; trap - TERM; exit 1' TERM HUP
     # check if an option to download a playlist was selected
     if [[ "$playlist" == 'true' ]]; then
         # cache download data so we only have to download it once
@@ -110,9 +113,8 @@ while true; do
         fi
     fi
     # trap exit and interrupt to cleanup a notification
-    trap 'termux-notification --id $randid --group "downloadfailed" --title "Download Failed" --content "$vidtitle";  termux-wake-unlock; trap - INT TERM; kill -s INT "$$"' INT
-    trap 'termux-notification --id $randid --group "downloadfailed" --title "Download Failed" --content "$vidtitle"; termux-wake-unlock; trap - TERM; exit 1' TERM HUP 
-
+    trap 'termux-notification --id $randid --group "downloadfailed" --title "Download Failed" --content "$vidtitle"; rm $randid-*.info.json; termux-wake-unlock; trap - INT TERM; kill -s INT "$$"' INT
+    trap 'termux-notification --id $randid --group "downloadfailed" --title "Download Failed" --content "$vidtitle"; rm $randid-*.info.json; termux-wake-unlock; trap - TERM; exit 1' TERM HUP
 
     termux-notification --id $randid --ongoing --group 'downloading' --title "Downloading" --content "$vidtitle"
     echo "Beginning Download"
@@ -123,6 +125,8 @@ while true; do
         youtube-dl --load-info-json "$jsonfile" $command
         return=$?
     done
+    # remove json files
+    rm $randid-*.info.json
     termux-wake-unlock
     if [[ $return -eq 0 ]]; then
         termux-notification --id $randid --group 'downloadfinished' --title "Download Finished" --content "$vidtitle"
